In [1]:
str(1)

'1'

In [2]:
def printvalue(n):
    print(str(n))
    
printvalue(1)

1


In [3]:
def printvalue(s1,s2):
    print(int(s1)+int(s2))
    
printvalue("3","4")

7


In [4]:
def printvalue(s1,s2):
    print(s1+s2)
    
printvalue("3","4")

34


In [9]:
def printvalue(s1,s2):
    len1=len(s1)
    len2=len(s2)
    if len1>len2:
        print(s1)
    elif len2>len1:
        print(s2)
    else:
        print(s1,'\n',s2)
        
printvalue("one","three")

three


In [13]:
def checkvalue(n):
    if n%2==0:
        print("it is even")
    else:
        print("it is odd")
checkvalue(7)
    

it is odd


In [24]:
def printDict(n):
    d=dict()
    for i in range(1,n+1):
        d[i]=i**2
    return d

printDict(5)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [26]:
def printlist():
    print(list(map(lambda x:x**2,range(1,21)))[:5])
    
printlist()

[1, 4, 9, 16, 25]


In [27]:
def printlist():
    result=list(map(lambda x:x**2,range(1,21)))[:5]
    print(result[:5])
    
printlist()

[1, 4, 9, 16, 25]


In [32]:
t=range(1,10)
print(list(t))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
t=(1,2,3,4,5,6,7,8,9,10)
a=len(t)
t[:a//2]


(1, 2, 3, 4, 5)

In [38]:
t[a//2:]

(6, 7, 8, 9, 10)

In [39]:
t=(1,2,3,4,5,6,7,8,9,10)
list(filter(lambda x:x%2==0,t))

[2, 4, 6, 8, 10]

In [43]:
t=(1,2,3,4,5,6,7,8,9,10)
result=[]
for i in t:
    if i%2==0:
        result.append(i)
        
tuple(result)

(2, 4, 6, 8, 10)

In [47]:
s=input('enter :')
if s=='yes' or s=='YES' or s=='Yes':
    print('yes')
else:
        print('no')

enter :yEs
no


In [50]:
t=list(range(1,11))
t

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [53]:
list(map(lambda t:t**2,filter(lambda t:t%2==0,t)))

[4, 16, 36, 64, 100]

In [54]:
import numpy as np

In [56]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.linspace(9,7,15)

array([9.        , 8.85714286, 8.71428571, 8.57142857, 8.42857143,
       8.28571429, 8.14285714, 8.        , 7.85714286, 7.71428571,
       7.57142857, 7.42857143, 7.28571429, 7.14285714, 7.        ])

In [69]:
array=np.arange(0,100)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [75]:
array.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
np.random.random((5,9))

array([[0.93365401, 0.27023157, 0.98373907, 0.11428952, 0.55977249,
        0.30315761, 0.77254594, 0.21604974, 0.04889997],
       [0.44308619, 0.17326967, 0.71588331, 0.03129099, 0.6334297 ,
        0.89987407, 0.92842372, 0.03221033, 0.15706852],
       [0.06637289, 0.25957389, 0.2622918 , 0.26355589, 0.83730951,
        0.61977527, 0.01262961, 0.11561051, 0.60773719],
       [0.25706068, 0.126714  , 0.39151747, 0.27100849, 0.49289377,
        0.9951021 , 0.66933753, 0.03016002, 0.90044462],
       [0.86562344, 0.84908546, 0.41375005, 0.92552741, 0.77541377,
        0.52139227, 0.16243618, 0.44388395, 0.27590449]])

In [88]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [89]:
array[3]

3

In [90]:
array(3)

TypeError: 'numpy.ndarray' object is not callable

In [92]:
a=array.reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [93]:
a[1,1]

11

In [94]:
a[5,7]

57

In [95]:
a[0,1]

1

In [96]:
a[1,0]

10

In [97]:
a[7,5]

75

In [98]:
a[0,9]

9